### ISSUE TITLE
An error occurred while running semantic-release: Error: Cannot find module 'xxxxx' with 4.1.0

### ISSUE THREAD

**Issue by Decklyn-Mac** [cycjimmy/semantic-release-action#201]
**Describe the bug**

The issue I'm getting is that, with the 4.1.0 version I'm getting the above error where it cannot find the modules for conventional-changelog-conventionalcommits, I'm currently using github actions for this.

**Workflow**

My Github Actions workflow step is here

`            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v4.1.0
              id: semantic   # Need an `id` for output variables
              with:
                branch: main
                extra_plugins: |
                  conventional-changelog-conventionalcommits@6.1.0
                  semantic-release-ms-teams@2.1.0
                  aggregate-error@3.1.0
                # working_directory: ./src/{{ inputs.application_name }}
              env:
                GH_TOKEN: ${{ secrets.gh_access_token }}
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}`
                
--------

Here is the error 

`Run cycjimmy/semantic-release-action@v4.1.0

added 351 packages, and audited 571 packages in 7s

[9](https://github.com/teehee/nottellingyou.com/actions/runs/8550274079/job/23427307224#step:9:10)7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

[6:41:50 AM] [semantic-release] › ℹ  Running semantic-release version 23.0.7
[6:41:50 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[6:41:50 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[6:41:50 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[6:41:50 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[6:41:50 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[6:41:50 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[6:41:50 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[6:41:50 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[6:41:50 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[6:41:52 AM] [semantic-release] › ✔  Run automated release from branch main on repository https://github.com/teeheenottelling/nottellingyou.com
[6:41:53 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[6:41:53 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[6:41:53 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
[6:41:53 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[6:41:53 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[6:41:53 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[6:41:53 AM] [semantic-release] › ℹ  No git tag version found on branch main
[6:41:53 AM] [semantic-release] › ℹ  No previous release found, retrieving all commits
[6:41:53 AM] [semantic-release] › ℹ  Found 42 commits since last release
[6:41:53 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[6:41:53 AM] [semantic-release] › ✘  Failed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[6:41:53 AM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Cannot find module 'conventional-changelog-conventionalcommits'
Error: Error: Cannot find module 'conventional-changelog-conventionalcommits'
    at importFrom (file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4.1.0/node_modules/import-from-esm/index.js:[10](https://github.com/teehee/nottellingyou.com/actions/runs/8550274079/job/23427307224#step:9:11)0:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async default (file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4.1.0/node_modules/@semantic-release/commit-analyzer/lib/load-parser-config.js:25:63)
    at async analyzeCommits (file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4.1.0/node_modules/@semantic-release/commit-analyzer/index.js:31:18)
    at async validator (file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4.1.0/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
    at async file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4.1.0/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
    at async file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4.1.0/node_modules/semantic-release/lib/plugins/pipeline.js:32:5
    at async pluginsConfigAccumulator.<computed> [as analyzeCommits] (file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4.1.0/node_modules/semantic-release/lib/plugins/index.js:87:[11](https://github.com/teehee/nottellingyou.com/actions/runs/8550274079/job/23427307224#step:9:12))
    at async run (file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4.1.0/node_modules/semantic-release/index.js:[17](https://github.com/teehee/nottellingyou.com/actions/runs/8550274079/job/23427307224#step:9:18)5:11)
    at async Module.default (file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4.1.0/node_modules/semantic-release/index.js:278:22) {
  code: 'MODULE_NOT_FOUND',
  pluginName: '@semantic-release/commit-analyzer'`
  
  
**Expected behavior**
Earlier in my pipeline I also add the below to make sure that its ready but it doesnt seem to be picked up by the action provided by yourself,  it does complete inside of the previous step but maybe its the npm audit or something not sure.

            - name: Install conventional commits dependencies
              run: |
                yarn add -D conventional-changelog-conventionalcommits@6.1.0
                yarn add -D semantic-release-ms-teams@2.1.0
                yarn add -D aggregate-error@3.1.0
                YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install
                

**Additional context**
I was able to fix it by reducing the action version to 

cycjimmy/semantic-release-action@v3.4.1

This is also a heads up to help people who might pop into this issue.

**Comment by ajfranzoia** [comment]
In my case I was able to fix it by downgrading the plugin version to `conventional-changelog-conventionalcommits@v5`.

**Comment by iuscare** [comment]
I encountered the same error. It occurred after the checkout action was deprecated in version 2 due to the end of support for Node 16. When I switched to action version 4, the error appeared. I can also confirm that the solution provided by @ajfranzoia resolved the issue for now

**Comment by rbardini** [comment]
Pinning the semantic-release version to 24 (latest at the time of this comment) worked for me:

```yml
      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24
          extra_plugins: |
            conventional-changelog-conventionalcommits
```
