### ISSUE TITLE
ESM fail

### ISSUE THREAD

**Issue by RukshanJS** [cycjimmy/semantic-release-action#204]
Error: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/index.js from /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/src/index.js not supported.

**Comment by vvanouytsel** [comment]
When using `v4.1.0`, I now get the following error:

```
 [5:19:18 PM] [semantic-release] › ✘  An error occurred while running semantic-release: RangeError: Invalid time value
    at committerDate (/home/runner/work/_actions/cycjimmy/semantic-release-action/v4.1.0/node_modules/conventional-changelog-writer/index.js:80:30)
    at /home/runner/work/_actions/cycjimmy/semantic-release-action/v4.1.0/node_modules/conventional-changelog-writer/lib/util.js:202:17
    at Array.forEach (<anonymous>)
    at processCommit (/home/runner/work/_actions/cycjimmy/semantic-release-action/v4.1.0/node_modules/conventional-changelog-writer/lib/util.js:198:31)
    at /home/runner/work/_actions/cycjimmy/semantic-release-action/v4.1.0/node_modules/conventional-changelog-writer/index.js:123:32 {
  pluginName: '@semantic-release/release-notes-generator'
}
Error: RangeError: Invalid time value
```


```yaml
      - name: Check semantic release
        uses: cycjimmy/semantic-release-action@v4.1.0
```
