### ISSUE TITLE
Error: RangeError: Invalid time value

### ISSUE THREAD

**Issue by MrGadget1024** [cycjimmy/semantic-release-action#205]
**Describe the bug**
```
[2:21:10 PM] [semantic-release] » i  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[2:21:10 PM] [semantic-release] » ×  Failed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[2:21:10 PM] [semantic-release] » ×  An error occurred while running semantic-release: RangeError: Invalid time value
    at committerDate (D:\a\_actions\cycjimmy\semantic-release-action\v4\node_modules\conventional-changelog-writer\index.js:80:30)
    at D:\a\_actions\cycjimmy\semantic-release-action\v4\node_modules\conventional-changelog-writer\lib\util.js:202:17
    at Array.forEach (<anonymous>)
    at processCommit (D:\a\_actions\cycjimmy\semantic-release-action\v4\node_modules\conventional-changelog-writer\lib\util.js:198:31)
    at D:\a\_actions\cycjimmy\semantic-release-action\v4\node_modules\conventional-changelog-writer\index.js:123:32 {
  pluginName: '@semantic-release/release-notes-generator'
}
Error: RangeError: Invalid time value
```

**Workflow**
https://github.com/MirrorNetworking/Mirror/blob/master/.github/workflows/Semantic.yml
https://github.com/MirrorNetworking/Mirror/blob/master/.releaserc.yml

**Expected behavior**
No error.

**Additional context**
https://github.com/MirrorNetworking/Mirror/actions/runs/8951133306/job/24587140924

**Comment by vsarunas** [comment]
This is upstream error https://github.com/semantic-release/release-notes-generator/issues/633

**Comment by vvanouytsel** [comment]
Any way to work around this?
