### ISSUE TITLE
Git tag is missing the tag message option

### ISSUE THREAD

**Issue by TomerFi** [cycjimmy/semantic-release-action#75]
**Describe the bug**

When trying to release with this action,
reaching the `tag` phase,
and failing because the command is missing the `tag message (-m)` option.

From the log:

```text
[7:24:39 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: git tag 2.0.0 d48765deedc5524eb46c6047ea66d4efcd31e189
error: Terminal is dumb, but EDITOR unset
Please supply the message using either -m or -F option.
    at makeError (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2.5.4/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2.5.4/node_modules/execa/index.js:118:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async tag (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2.5.4/node_modules/semantic-release/lib/git.js:224:3)
    at async run (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2.5.4/node_modules/semantic-release/index.js:191:5)
    at async module.exports (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2.5.4/node_modules/semantic-release/index.js:260:22)
    at async release (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2.5.4/src/index.js:25:18) {
  shortMessage: 'Command failed with exit code 1: git tag 2.0.0 d48765deedc5524eb46c6047ea66d4efcd31e189',
  command: 'git tag 2.0.0 d48765deedc5524eb46c6047ea66d4efcd31e189',
  escapedCommand: 'git tag 2.0.0 d48765deedc5524eb46c6047ea66d4efcd31e189',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'error: Terminal is dumb, but EDITOR unset\n' +
    'Please supply the message using either -m or -F option.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Error: Error: Command failed with exit code 1: git tag 2.0.0 d48765deedc5524eb46c6047ea66d4efcd31e189
error: Terminal is dumb, but EDITOR unset
Please supply the message using either -m or -F option.
```

**Workflow**

[A failed run](https://github.com/TomerFi/hebcal-api/runs/3159104877?check_suite_focus=true)
[The workflow](https://github.com/TomerFi/hebcal-api/actions/runs/1066550689/workflow)

**Expected behavior**

I think a feature that allows setting a custom message will be a nice feature.
But for the time being, perhaps use the tag version as a tag message as well.

**Additional context**

I'm not sure at all this issue belongs here,
It looks like an issue with the underlining `semantic-release` module.
Nevertheless, I thought I should start here...

**Comment by TomerFi** [comment]
After skipping the action, trying to work directly with the module, and experiencing the same issue.
I've open this [here](https://github.com/semantic-release/github/issues/393) instead.
